name: NPM release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Build package
      run: yarn build
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 17.1.1  # It is recommended to specify specifying version range
                                    # for semantic-release.
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
